[package]
name = "colang-interpreter"
version = "0.1.0"
authors = ["Pavel Senchanka <pavel.senchanka@gmail.com>"]
edition = "2018"


[dependencies]
colang = { path = "../colang" }
codespan-reporting = "0.9.1"
